"use client"
import AuthWrapper from './AuthWrapper';
import { User } from 'firebase/auth';
import { useState, useMemo, useRef, useEffect } from "react";
import { LineChart, Line, XAxis, YAxis, Tooltip, ResponsiveContainer, BarChart, Bar, CartesianGrid, ReferenceLine } from "recharts";
import { db } from './firebase';
import { doc, setDoc, getDoc, collection, getDocs, deleteDoc } from 'firebase/firestore';

const DAYS=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"],TDI=(new Date().getDay()+6)%7,uid=()=>"_"+Math.random().toString(36).slice(2,9),rnd=(v:any)=>Math.round(v/2.5)*2.5,e1rm=(w:any,r:any)=>r<=1?w:Math.round(w*(1+r/30)),fd=(d:any)=>new Date(d+"T12:00:00").toLocaleDateString("en-US",{month:"short",day:"numeric"}),td=new Date().toISOString().split("T")[0];
const vol=(ex:any)=>ex.sets.filter((s:any)=>s.type!=="warmup").reduce((t:any,s:any)=>{let v=(s.r||0)*(s.w||0);if(s.drops)s.drops.forEach((d:any)=>{v+=(d.r||0)*(d.w||0);});return t+v;},0);
const MG={"Bench Press":"Chest","Incline DB Press":"Chest","OHP":"Shoulders","Lateral Raise":"Shoulders","Tricep Pushdown":"Triceps","Deadlift":"Back","Barbell Row":"Back","Lat Pulldown":"Back","Face Pull":"Back","Bicep Curl":"Biceps","Squat":"Quads","Leg Press":"Quads","Romanian Deadlift":"Hamstrings","Calf Raise":"Calves","Leg Curl":"Hamstrings"};
const C={bg:"#0a0a0f",cd:"#13131d",bd:"#1e1e2e",ac:"#6c5ce7",tx:"#e2e2e8",dm:"#8888a0",gn:"#00cec9",rd:"#ff6b6b",yl:"#feca57",or:"#fdcb6e",gd:"#f9ca24",inn:"#0e0e18"};
const B=(a:any)=>({padding:"8px 16px",borderRadius:8,border:"none",background:a?C.ac:"transparent",color:a?"#fff":C.dm,cursor:"pointer",fontSize:14,fontWeight:500});
const CR={background:C.cd,borderRadius:12,border:`1px solid ${C.bd}`,padding:20,marginBottom:16};
const IN={background:"#1a1a2e",border:`1px solid ${C.bd}`,borderRadius:8,padding:"8px 12px",color:C.tx,fontSize:14,outline:"none",width:"100%",boxSizing:"border-box"};
const STS=[{id:"normal",l:"Working",c:C.tx},{id:"warmup",l:"Warm-up",c:C.yl},{id:"drop",l:"Drop Set",c:C.or}];
const DT=[{id:"push",name:"Push Day",exercises:[{name:"Bench Press",sets:4},{name:"OHP",sets:3},{name:"Incline DB Press",sets:3},{name:"Tricep Pushdown",sets:3},{name:"Lateral Raise",sets:3}]},{id:"pull",name:"Pull Day",exercises:[{name:"Deadlift",sets:3},{name:"Barbell Row",sets:3},{name:"Lat Pulldown",sets:3},{name:"Bicep Curl",sets:3},{name:"Face Pull",sets:3}]},{id:"legs",name:"Leg Day",exercises:[{name:"Squat",sets:4},{name:"Leg Press",sets:3},{name:"Romanian Deadlift",sets:3},{name:"Calf Raise",sets:3},{name:"Leg Curl",sets:3}]},{id:"rest",name:"Rest",exercises:[]}];
const DS={Monday:"push",Tuesday:"pull",Wednesday:"rest",Thursday:"legs",Friday:"push",Saturday:"pull",Sunday:"rest"};

function DD({trigger,children,open,onClose}:any){const r=useRef();useEffect(()=>{if(!open)return;const h=e=>{if(r.current&&!r.current.contains(e.target))onClose();};document.addEventListener("mousedown",h);return()=>document.removeEventListener("mousedown",h);},[open,onClose]);return <div ref={r} style={{position:"relative",display:"inline-block"}}>{trigger}{open&&<div style={{position:"absolute",top:"100%",left:0,marginTop:4,zIndex:50,background:C.cd,border:`1px solid ${C.bd}`,borderRadius:10,padding:4,minWidth:220,boxShadow:"0 8px 32px rgba(0,0,0,.6)",maxHeight:300,overflowY:"auto"}}>{children}</div>}</div>;}
function DI({children,onClick,active,color}:any){return <div onClick={onClick} style={{padding:"8px 12px",borderRadius:8,cursor:"pointer",fontSize:14,color:color||C.tx,background:active?C.ac+"22":"transparent"}} onMouseEnter={e=>e.currentTarget.style.background=C.bd} onMouseLeave={e=>e.currentTarget.style.background=active?C.ac+"22":"transparent"}>{children}</div>;}
const PCC=[C.ac,C.gn,C.rd,C.yl,C.or,"#a29bfe","#fd79a8"];
function PerfCharts({perfData:pD,prDates:pDt,latestPerf:lP}:any){const[mode,sM]=useState("perf"),[mDd,sMD]=useState(false);
const names=[...new Set(pD.filter(p=>p.name!=="Rest").map(p=>p.name))];const ss={};names.forEach(n=>{ss[n]=pD.filter(p=>p.name===n).map((p,i)=>({...p,idx:i+1}));});const ml=Math.max(...Object.values(ss).map(a=>a.length));const tks=[];for(let i=1;i<=ml;i++)tks.push(i);
const merged=tks.map(i=>{const row={idx:i};names.forEach(n=>{const s=ss[n];if(s[i-1]){row[n]=s[i-1].score;if(pDt[s[i-1].date])row[n+"_pr"]=true;}});return row;});
const cumul=[{idx:0,...Object.fromEntries(names.map(n=>[n,0]))},...tks.map(i=>{const row={idx:i};names.forEach(n=>{const s=ss[n];if(!s[i-1]){row[n]=null;return;}let t=0;for(let j=0;j<=i-1;j++)if(s[j])t+=s[j].score-100;row[n]=Math.round(t);});return row;})];
const leg=names.map((n,i)=><span key={n} style={{display:"flex",alignItems:"center",gap:4,color:C.dm}}><span style={{width:10,height:10,borderRadius:5,background:PCC[i%PCC.length],display:"inline-block"}}/>{n}</span>);
const data=mode==="perf"?merged:cumul;
const yDom=mode==="perf"?[60,140]:undefined;
const refY=mode==="perf"?100:0;
const fmtTip=mode==="perf"?(v,n)=>[v+"%",n]:(v,n)=>[(v>0?"+":"")+v,n];
return <><div style={CR}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}>
<DD open={mDd} onClose={()=>sMD(false)} trigger={<button onClick={()=>sMD(!mDd)} style={{background:"none",border:"none",color:C.tx,fontSize:15,fontWeight:600,cursor:"pointer",display:"flex",alignItems:"center",gap:6,padding:0}}>{mode==="perf"?"Performance Index":"Cumulative Growth"} <span style={{color:C.dm,fontSize:10}}>▼</span></button>}>
<DI active={mode==="perf"} onClick={()=>{sM("perf");sMD(false);}}>Performance Index</DI>
<DI active={mode==="cumul"} onClick={()=>{sM("cumul");sMD(false);}}>Cumulative Growth</DI>
</DD>
</div>
<ResponsiveContainer width="100%" height={220}><LineChart data={data}><CartesianGrid strokeDasharray="3 3" stroke={C.bd}/><XAxis dataKey="idx" tick={{fill:C.dm,fontSize:11}}/><YAxis tick={{fill:C.dm,fontSize:11}} domain={yDom}/><Tooltip contentStyle={{background:C.cd,border:`1px solid ${C.bd}`,borderRadius:8,color:C.tx,fontSize:12}} formatter={fmtTip}/><ReferenceLine y={refY} stroke={C.dm} strokeDasharray="4 4"/>
{mode==="perf"?names.map((n,i)=><Line key={n} type="monotone" dataKey={n} stroke={PCC[i%PCC.length]} strokeWidth={2} connectNulls dot={p=>{if(p.payload[n]==null)return null;const pr=p.payload[n+"_pr"];return <circle cx={p.cx} cy={p.cy} r={pr?6:3} fill={pr?C.gd:PCC[i%PCC.length]} stroke={pr?"#fff":"none"} strokeWidth={pr?2:0}/>;}}/>):names.map((n,i)=><Line key={n} type="monotone" dataKey={n} stroke={PCC[i%PCC.length]} strokeWidth={2} dot={{fill:PCC[i%PCC.length],r:3}} connectNulls/>)}
</LineChart></ResponsiveContainer>
<div style={{marginTop:12,display:"flex",gap:16,justifyContent:"center",flexWrap:"wrap",fontSize:12}}>{leg}{mode==="perf"&&<span style={{display:"flex",alignItems:"center",gap:4,color:C.dm}}><span style={{width:10,height:10,borderRadius:5,background:C.gd,display:"inline-block"}}/>PR</span>}</div>
</div>
{lP&&lP.detail.length>0&&<div style={CR}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}><h3 style={{margin:0,fontSize:15,fontWeight:600}}>Last Session</h3><span style={{fontSize:20,fontWeight:700,color:lP.score>=100?C.gn:lP.score>=90?C.yl:C.rd}}>{lP.score}%</span></div>
{lP.detail.map((d,i)=>{const col=d.pct>=100?C.gn:d.pct>=90?C.yl:C.rd;return <div key={i} style={{display:"flex",alignItems:"center",gap:12,padding:"8px 0",borderTop:i?`1px solid ${C.bd}`:"none"}}><span style={{width:40,textAlign:"center",fontSize:16,fontWeight:700,color:col}}>{d.pct}%</span><div style={{flex:1}}><div style={{background:C.bd,borderRadius:4,height:6,overflow:"hidden"}}><div style={{height:6,borderRadius:4,background:col,width:`${Math.min(d.pct,150)/1.5}%`}}/></div></div><div style={{width:140,textAlign:"right"}}><span style={{fontSize:13,fontWeight:500}}>{d.name}</span><span style={{fontSize:11,marginLeft:8,color:d.delta.startsWith("+")?C.gn:d.delta==="matched"?C.dm:C.rd}}>{d.delta}</span></div></div>})}</div>}</>;}

function Dashboard({ user, handleSignOut }:any){
const[view,sv]=useState("today"),[tmpls,sT]=useState(DT),[sched,sS]=useState(DS),[hist,sH]=useState([]),[eTmpl,sET]=useState(null),[selW,sSW]=useState(null),[sess,sSS]=useState(null),[oDd,sOD]=useState(null),[nTN,sNTN]=useState(""),[shNT,sSNT]=useState(false),[tOvr,sTO]=useState(null),[tDd,sTD]=useState(false),[favs,sF]=useState({}),[expPR,sEP]=useState(null),[pausedSess,sPS]=useState(null),[addDd,sAD]=useState(false),[newEx,sNE]=useState(null),[newLibEx,sNLE]=useState(null),[loading,setLoading]=useState(true),[workoutDate,sWD]=useState(td);

useEffect(()=>{
  const loadData = async()=>{
    try{
      const userDoc = await getDoc(doc(db,'users',user.uid));
      if(userDoc.exists()){
        const data = userDoc.data();
        if(data.templates)sT(data.templates);
        if(data.schedule)sS(data.schedule);
      }
      const workoutsSnap = await getDocs(collection(db,'users',user.uid,'workouts'));
      const workouts = [];
      workoutsSnap.forEach(doc=>workouts.push({id:doc.id,...doc.data()}));
      sH(workouts.sort((a,b)=>a.date.localeCompare(b.date)));
    }catch(e){console.error('Load error:',e);}
    setLoading(false);
  };
  loadData();
},[user.uid]);

const saveTemplates = async(newTemplates)=>{
  try{
    await setDoc(doc(db,'users',user.uid),{templates:newTemplates},{merge:true});
  }catch(e){console.error('Save templates error:',e);}
};

const saveSchedule = async(newSchedule)=>{
  try{
    await setDoc(doc(db,'users',user.uid),{schedule:newSchedule},{merge:true});
  }catch(e){console.error('Save schedule error:',e);}
};

const saveWorkout = async(workout)=>{
  try{
    await setDoc(doc(db,'users',user.uid,'workouts',workout.id),workout);
  }catch(e){console.error('Save workout error:',e);}
};

const tDay=DAYS[TDI],gT=id=>tmpls.find(t=>t.id===id)||{name:"Rest",exercises:[]},tTid=tOvr||sched[tDay],tTmpl=gT(tTid);
const allEx=useMemo(()=>{const s=new Set();hist.forEach(w=>w.exercises.forEach(e=>s.add(e.name)));tmpls.forEach(t=>t.exercises.forEach(e=>s.add(e.name)));return[...s].sort();},[hist,tmpls]);
const exByMG=useMemo(()=>{const m={};allEx.forEach(n=>{const g=MG[n]||"Other";if(!m[g])m[g]=[];m[g].push(n);});return m;},[allEx]);
const gP=n=>{for(let i=hist.length-1;i>=0;i--){const e=hist[i].exercises.find(x=>x.name===n);if(e)return e;}return null;};
const prs=useMemo(()=>{const m={};hist.forEach(w=>w.exercises.forEach(ex=>{if(!m[ex.name])m[ex.name]={hist:[],best:0,bDate:"",prev:0,sets:[]};const b=ex.sets.filter(s=>s.type!=="warmup").reduce((b2,s)=>Math.max(b2,e1rm(s.w,s.r)),0);if(b>0){if(b>m[ex.name].best){m[ex.name].prev=m[ex.name].best;m[ex.name].best=b;m[ex.name].bDate=w.date;}m[ex.name].hist.push({date:w.date,e1rm:b,fd:fd(w.date)});ex.sets.filter(s=>s.type!=="warmup").forEach(s=>m[ex.name].sets.push({date:w.date,fd:fd(w.date),w:s.w,r:s.r}));}}));return m;},[hist]);
const prDates=useMemo(()=>{const d={};Object.entries(prs).forEach(([n,x])=>{if(x.bDate){if(!d[x.bDate])d[x.bDate]=[];d[x.bDate].push(n);}});return d;},[prs]);
const todayW=useMemo(()=>hist.find(w=>w.date===td),[hist]);
const selDateW=useMemo(()=>hist.find(w=>w.date===workoutDate),[hist,workoutDate]);
const perfData=useMemo(()=>{const byN={};hist.forEach(w=>{if(!byN[w.name])byN[w.name]=[];byN[w.name].push(w);});return hist.map(w=>{const arr=byN[w.name],idx=arr.indexOf(w);if(idx===0)return{date:w.date,fd:fd(w.date),name:w.name,score:100,detail:[]};const prev=arr[idx-1];let tp=0,mp=0;const det=[];
w.exercises.forEach(ex=>{const pEx=prev.exercises.find(e=>e.name===ex.name);if(!pEx)return;const wS=ex.sets.filter(s=>s.type!=="warmup"),pS=pEx.sets.filter(s=>s.type!=="warmup"),cnt=Math.max(wS.length,pS.length);let ep=0,em=0;for(let i=0;i<cnt;i++){const cs=wS[i],pss=pS[i];if(!pss){ep+=1;em+=1;continue;}if(!cs){em+=1;continue;}ep+=Math.min(pss.w*pss.r>0?(cs.w*cs.r)/(pss.w*pss.r):1,1.5);em+=1;}const pct=em>0?Math.round(ep/em*100):100;
const cB=Math.max(...wS.map(s=>s.w)),pB=Math.max(...pS.map(s=>s.w)),cR=wS.reduce((t,s)=>t+s.r,0),pR=pS.reduce((t,s)=>t+s.r,0);let delta=cB>pB?`+${rnd(cB-pB)} lbs`:cR>pR?`+${cR-pR} reps`:cB===pB&&cR===pR?"matched":cB<pB?`${rnd(cB-pB)} lbs`:`${cR-pR} reps`;
det.push({name:ex.name,pct,delta});tp+=ep;mp+=em;});return{date:w.date,fd:fd(w.date),name:w.name,score:mp>0?Math.round(tp/mp*100):100,detail:det};});},[hist]);
const latestPerf=perfData.length>0?perfData[perfData.length-1]:null;
const streak=useMemo(()=>{let c=0;const d=new Date();d.setHours(12);for(let i=0;i<365;i++){const ds=d.toISOString().split("T")[0],di=(d.getDay()+6)%7;if(sched[DAYS[di]]==="rest"){d.setDate(d.getDate()-1);continue;}if(hist.some(h=>h.date===ds))c++;else if(ds!==td)break;d.setDate(d.getDate()-1);}return c;},[hist,sched]);
const wkSt=useMemo(()=>{const now=new Date();now.setHours(12);const mo=new Date(now);mo.setDate(now.getDate()-(now.getDay()+6)%7);return DAYS.map((_,i)=>{const d=new Date(mo);d.setDate(mo.getDate()+i);const ds=d.toISOString().split("T")[0];return{isR:sched[DAYS[i]]==="rest",w:hist.some(h=>h.date===ds),past:d<now&&i!==TDI,isTd:i===TDI,pr:!!prDates[ds]};});},[hist,sched,prDates]);

const uTN=(id,v)=>{const newT=tmpls.map(t=>t.id===id?{...t,name:v}:t);sT(newT);saveTemplates(newT);};
const aTEx=id=>{const newT=tmpls.map(t=>t.id===id?{...t,exercises:[...t.exercises,{name:"",sets:3}]}:t);sT(newT);saveTemplates(newT);};
const uTEx=(id,i,f,v)=>{const newT=tmpls.map(t=>t.id===id?{...t,exercises:t.exercises.map((e,j)=>j===i?{...e,[f]:v}:e)}:t);sT(newT);saveTemplates(newT);};
const rTEx=(id,i)=>{const newT=tmpls.map(t=>t.id===id?{...t,exercises:t.exercises.filter((_,j)=>j!==i)}:t);sT(newT);saveTemplates(newT);};
const mTEx=(id,i,d)=>{const newT=tmpls.map(t=>{if(t.id!==id)return t;const to=i+d;if(to<0||to>=t.exercises.length)return t;const a=[...t.exercises];[a[i],a[to]]=[a[to],a[i]];return{...t,exercises:a};});sT(newT);saveTemplates(newT);};
const cTmpl=()=>{if(!nTN.trim())return;const id=uid();const newT=[...tmpls,{id,name:nTN.trim(),exercises:[]}];sT(newT);saveTemplates(newT);sNTN("");sSNT(false);sET(id);};
const dTmpl=id=>{const ns={...sched};DAYS.forEach(d=>{if(ns[d]===id)ns[d]="rest";});sS(ns);saveSchedule(ns);const newT=tmpls.filter(t=>t.id!==id);sT(newT);saveTemplates(newT);};

const startS=(tmpl,existing,date)=>{const wDate=date||workoutDate;if(existing){sSS({lb:existing.name,exs:existing.exercises.map(ex=>({name:ex.name,sets:ex.sets.map(s=>({w:""+s.w,r:""+s.r,type:s.type||"normal",note:s.note||"",nt:"",drops:s.drops?s.drops.map(d=>({w:""+d.w,r:""+d.r})):[]})),cs:ex.sets.length-1,ps:[]})),ce:0,eid:existing.id,date:wDate});return;}if(!tmpl||!tmpl.exercises.length)return;sSS({lb:tmpl.name,exs:tmpl.exercises.map(te=>{const p=gP(te.name),sets=[];for(let i=0;i<te.sets;i++){const ps=p&&p.sets[i];sets.push({w:ps?""+rnd(ps.w+2.5):"",r:ps?""+ps.r:"",type:"normal",note:"",nt:"",drops:[]});}return{name:te.name,sets,cs:0,ps:p?p.sets:[]};}),ce:0,eid:null,date:wDate});};
const uS=(ei,si,f,v)=>sSS(s=>({...s,exs:s.exs.map((e,i)=>i===ei?{...e,sets:e.sets.map((st,j)=>j===si?{...st,[f]:v}:st)}:e)}));
const addExS=(name,ns)=>{if(sess.exs.some(e=>e.name===name)){alert("Exercise already in workout");return;}const p=gP(name),sets=[];for(let i=0;i<ns;i++){const ps=p&&p.sets[i];sets.push({w:ps?""+rnd(ps.w+2.5):"",r:ps?""+ps.r:"",type:"normal",note:"",nt:"",drops:[]});}sSS(s=>({...s,exs:[...s.exs,{name,sets,cs:0,ps:p?p.sets:[]}]}));sAD(false);sNE(null);};
const finS=()=>{const exs=sess.exs.map(e=>({name:e.name,sets:e.sets.filter(s=>s.w&&s.r).map(s=>({w:+s.w,r:+s.r,type:s.type,note:s.nt&&s.note?s.nt+": "+s.note:s.note||"",drops:s.drops?s.drops.filter(d=>d.w&&d.r).map(d=>({w:+d.w,r:+d.r})):[]}))})).filter(e=>e.sets.length>0);if(exs.length>0){const wo={id:sess.eid||uid(),date:sess.date||workoutDate,name:sess.lb,exercises:exs};if(sess.eid){const newH=hist.map(h=>h.id===sess.eid?wo:h);sH(newH);saveWorkout(wo);}else{const newH=[...hist,wo].sort((a,b)=>a.date.localeCompare(b.date));sH(newH);saveWorkout(wo);}}sSS(null);sPS(null);sWD(td);sv("today");};

if(loading){return <div style={{background:C.bg,minHeight:"100vh",color:C.tx,fontFamily:"system-ui",display:"flex",alignItems:"center",justifyContent:"center"}}><div style={{textAlign:"center"}}><div style={{fontSize:32,marginBottom:16}}>💪</div><div>Loading...</div></div></div>;}

if(sess){const ex=sess.exs[sess.ce],set=ex.sets[ex.cs],ps=ex.ps[ex.cs],tE=sess.exs.length,tS=ex.sets.length,isL=ex.cs===tS-1,st=STS.find(t=>t.id===set.type)||STS[0];
return <div style={{background:C.bg,minHeight:"100vh",color:C.tx,fontFamily:"system-ui"}}><div style={{padding:"20px 24px",maxWidth:600,margin:"0 auto"}}>
<div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:8,gap:8}}><h2 style={{margin:0,fontSize:20}}>{sess.lb}</h2><div style={{display:"flex",gap:8}}><button onClick={finS} style={{...B(true),background:C.gn,fontSize:13,padding:"8px 14px"}}>Finish</button><button onClick={()=>{sPS(sess);sSS(null);sv("today");}} style={{...B(false),border:`1px solid ${C.bd}`,fontSize:13,padding:"8px 14px",color:C.dm}}>Back</button></div></div>
<div style={{background:C.bd,borderRadius:6,height:6,marginBottom:16}}><div style={{background:C.gn,borderRadius:6,height:6,width:`${(sess.ce/tE+(ex.cs+1)/tS/tE)*100}%`,transition:"width .3s"}}/></div>
<div style={{display:"flex",gap:6,marginBottom:16,overflowX:"auto",paddingBottom:4,alignItems:"center"}}>
{sess.exs.map((e,i)=>{const dn=e.sets.some(s=>s.w&&s.r);return <div key={i} style={{display:"flex",alignItems:"center",gap:4,padding:"6px 12px",borderRadius:20,border:`1px solid ${i===sess.ce?C.ac:dn?C.gn:C.bd}`,background:i===sess.ce?C.ac+"22":"transparent",color:i===sess.ce?C.ac:dn?C.gn:C.dm,fontSize:12,whiteSpace:"nowrap",flexShrink:0}}><span draggable onDragStart={ev=>ev.dataTransfer.setData("text",""+i)} onDragOver={ev=>ev.preventDefault()} onDrop={ev=>{ev.preventDefault();const f=+ev.dataTransfer.getData("text");if(f===i)return;sSS(s=>{const a=[...s.exs],[m]=a.splice(f,1);a.splice(i,0,m);let ce=s.ce;if(s.ce===f)ce=i;else if(f<s.ce&&i>=s.ce)ce--;else if(f>s.ce&&i<=s.ce)ce++;return{...s,exs:a,ce};});}} onClick={()=>sSS({...sess,ce:i})} style={{cursor:"grab"}}>{e.name}</span>{sess.exs.length>1&&<button onClick={(ev)=>{ev.stopPropagation();sSS(s=>{const newExs=s.exs.filter((_,idx)=>idx!==i);let newCe=s.ce;if(i===s.ce){newCe=Math.min(i,newExs.length-1);}else if(i<s.ce){newCe=s.ce-1;}return{...s,exs:newExs,ce:newCe};});}} style={{background:"none",border:"none",color:C.rd,cursor:"pointer",fontSize:14,padding:0,marginLeft:4,lineHeight:1}}>×</button>}</div>;})}
<div style={{flexShrink:0}}><button onClick={()=>{sAD(v=>!v);sNE(null);}} style={{width:28,height:28,borderRadius:14,border:`1px dashed ${C.ac}`,background:addDd?C.ac+"22":"transparent",color:C.ac,cursor:"pointer",fontSize:16,display:"flex",alignItems:"center",justifyContent:"center"}}>+</button>
{addDd&&<><div style={{position:"fixed",top:0,left:0,right:0,bottom:0,zIndex:40,background:"rgba(0,0,0,.3)"}} onClick={()=>{sAD(false);sNE(null);}}/><div style={{position:"fixed",top:"50%",left:"50%",transform:"translate(-50%,-50%)",zIndex:50,width:300,maxHeight:350,background:C.cd,border:`1px solid ${C.bd}`,borderRadius:12,boxShadow:"0 12px 40px rgba(0,0,0,.7)",display:"flex",flexDirection:"column",overflow:"hidden"}}>
<div style={{padding:"12px 12px 8px",borderBottom:`1px solid ${C.bd}`,fontSize:14,fontWeight:600}}>Add Exercise</div>
{newEx?<div style={{padding:12,display:"flex",flexDirection:"column",gap:8}}><input style={{...IN,fontSize:13}} placeholder="Exercise name" value={newEx.n} onChange={e=>sNE({...newEx,n:e.target.value})} autoFocus/><div style={{display:"flex",gap:8,alignItems:"center"}}><input type="number" style={{...IN,width:50,fontSize:13}} value={newEx.s} onChange={e=>sNE({...newEx,s:e.target.value})}/><span style={{color:C.dm,fontSize:12}}>sets</span></div><div style={{display:"flex",gap:6}}><button onClick={()=>{if(newEx.n)addExS(newEx.n,+(newEx.s)||3);}} style={{...B(true),fontSize:12,flex:1}}>Add</button><button onClick={()=>sNE(null)} style={{...B(false),fontSize:12}}>Back</button></div></div>:
<div style={{flex:1,overflowY:"auto",padding:4}}><div style={{borderBottom:`1px solid ${C.bd}`,paddingBottom:4,marginBottom:4}}><div onClick={()=>sNE({n:"",s:"3"})} style={{padding:"8px 10px",borderRadius:6,cursor:"pointer",fontSize:13,color:C.gn,fontWeight:500}} onMouseEnter={e=>e.currentTarget.style.background=C.bd} onMouseLeave={e=>e.currentTarget.style.background="transparent"}>+ New Exercise</div></div>
{Object.entries(exByMG).map(([g,xs])=><div key={g}><div style={{padding:"5px 10px",fontSize:9,color:C.dm,fontWeight:700,textTransform:"uppercase",letterSpacing:1}}>{g}</div>{xs.map(n=><div key={n} onClick={()=>addExS(n,3)} style={{padding:"6px 10px",borderRadius:6,cursor:"pointer",fontSize:13}} onMouseEnter={e=>e.currentTarget.style.background=C.bd} onMouseLeave={e=>e.currentTarget.style.background="transparent"}>{n}</div>)}</div>)}</div>}
</div></>}</div></div>
<div style={CR}><h3 style={{margin:"0 0 4px",fontSize:18,color:C.gn}}>{ex.name}</h3>
<div style={{display:"flex",gap:6,margin:"8px 0 16px"}}>{ex.sets.map((_,i)=>{const dn=i<ex.cs&&ex.sets[i].w&&ex.sets[i].r,cur=i===ex.cs;return <div key={i} onClick={()=>sSS(s=>({...s,exs:s.exs.map((e2,j)=>j===s.ce?{...e2,cs:i}:e2)}))} style={{width:cur?32:10,height:10,borderRadius:5,background:dn?C.gn:cur?C.ac:C.bd,cursor:"pointer"}}/>;})}</div>
{ps&&<div style={{background:C.inn,borderRadius:8,padding:12,marginBottom:16,border:`1px solid ${C.bd}`}}><div style={{fontSize:10,color:C.dm,marginBottom:6,fontWeight:700,textTransform:"uppercase"}}>Previous Set {ex.cs+1}</div><div style={{display:"flex",gap:24}}><div><span style={{color:C.dm,fontSize:12}}>Wt </span><span style={{fontSize:16,fontWeight:600}}>{ps.w}lbs</span></div><div><span style={{color:C.dm,fontSize:12}}>Reps </span><span style={{fontSize:16,fontWeight:600}}>{ps.r}</span></div></div></div>}
<div style={{display:"flex",gap:4,marginBottom:12}}>{STS.map(s2=><button key={s2.id} onClick={()=>uS(sess.ce,ex.cs,"type",s2.id)} style={{padding:"4px 10px",borderRadius:6,fontSize:11,fontWeight:600,border:`1px solid ${set.type===s2.id?s2.c:C.bd}`,background:set.type===s2.id?s2.c+"22":"transparent",color:set.type===s2.id?s2.c:C.dm,cursor:"pointer"}}>{s2.l}</button>)}</div>
<div style={{fontSize:13,color:C.dm,marginBottom:8,fontWeight:600}}>Set {ex.cs+1}/{tS} <span style={{color:st.c}}>{st.l}</span></div>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12,marginBottom:8}}><div><label style={{fontSize:11,color:C.dm}}>Weight</label><input type="number" step="2.5" style={{...IN,fontSize:20,padding:12,fontWeight:700,textAlign:"center"}} value={set.w} onChange={e=>sSS(s=>({...s,exs:s.exs.map((e2,i)=>i===s.ce?{...e2,sets:e2.sets.map((st2,j)=>j===e2.cs?{...st2,w:e.target.value}:st2)}:e2)}))} onBlur={e=>{if(e.target.value)uS(sess.ce,ex.cs,"w",""+rnd(+e.target.value));}} placeholder="--"/></div><div><label style={{fontSize:11,color:C.dm}}>Reps</label><input type="number" style={{...IN,fontSize:20,padding:12,fontWeight:700,textAlign:"center"}} value={set.r} onChange={e=>uS(sess.ce,ex.cs,"r",e.target.value)} placeholder="--"/></div></div>
{set.type==="drop"&&<div style={{marginBottom:8}}>{(set.drops||[]).map((d,di)=><div key={di} style={{display:"grid",gridTemplateColumns:"1fr 1fr 28px",gap:8,marginBottom:6}}><div><label style={{fontSize:10,color:C.or}}>Drop {di+1}</label><input type="number" style={{...IN,fontSize:14,padding:8,textAlign:"center"}} value={d.w} onChange={e=>sSS(s=>({...s,exs:s.exs.map((e2,i)=>i===s.ce?{...e2,sets:e2.sets.map((st2,j)=>j===e2.cs?{...st2,drops:st2.drops.map((dr,k)=>k===di?{...dr,w:e.target.value}:dr)}:st2)}:e2)}))} onBlur={e=>{if(e.target.value){const nv=""+rnd(+e.target.value);sSS(s=>({...s,exs:s.exs.map((e2,i)=>i===s.ce?{...e2,sets:e2.sets.map((st2,j)=>j===e2.cs?{...st2,drops:st2.drops.map((dr,k)=>k===di?{...dr,w:nv}:dr)}:st2)}:e2)}));}}} placeholder="wt"/></div><div><label style={{fontSize:10,color:C.or}}>Reps</label><input type="number" style={{...IN,fontSize:14,padding:8,textAlign:"center"}} value={d.r} onChange={e=>sSS(s=>({...s,exs:s.exs.map((e2,i)=>i===s.ce?{...e2,sets:e2.sets.map((st2,j)=>j===e2.cs?{...st2,drops:st2.drops.map((dr,k)=>k===di?{...dr,r:e.target.value}:dr)}:st2)}:e2)}))} placeholder="r"/></div><button onClick={()=>sSS(s=>({...s,exs:s.exs.map((e2,i)=>i===s.ce?{...e2,sets:e2.sets.map((st2,j)=>j===e2.cs?{...st2,drops:st2.drops.filter((_,k)=>k!==di)}:st2)}:e2)}))} style={{background:"none",border:"none",color:C.rd,cursor:"pointer",alignSelf:"end",paddingBottom:8}}>x</button></div>)}<button onClick={()=>sSS(s=>({...s,exs:s.exs.map((e2,i)=>i===s.ce?{...e2,sets:e2.sets.map((st2,j)=>j===e2.cs?{...st2,drops:[...(st2.drops||[]),{w:"",r:""}]}:st2)}:e2)}))} style={{...B(false),color:C.or,fontSize:12,padding:"4px 0"}}>+ Drop</button></div>}
<div style={{display:"flex",gap:6,marginTop:4}}>{["RIR","RPE","Note"].map(np=><button key={np} onClick={()=>uS(sess.ce,ex.cs,"nt",set.nt===(np==="Note"?"custom":np)?"":(np==="Note"?"custom":np))} style={{padding:"4px 10px",borderRadius:6,fontSize:11,border:`1px solid ${set.nt===(np==="Note"?"custom":np)?C.ac:C.bd}`,background:set.nt===(np==="Note"?"custom":np)?C.ac+"22":"transparent",color:set.nt===(np==="Note"?"custom":np)?C.ac:C.dm,cursor:"pointer"}}>{np}</button>)}</div>
{set.nt&&<input style={{...IN,fontSize:13,marginTop:8}} value={set.note} onChange={e=>uS(sess.ce,ex.cs,"note",e.target.value)} placeholder={set.nt==="RIR"?"Reps in reserve":set.nt==="RPE"?"Rate of exertion":"Note..."}/>}
{tS>1&&<button onClick={()=>sSS(s=>{const ns=ex.sets.filter((_,j)=>j!==ex.cs);return{...s,exs:s.exs.map((e,i)=>i===s.ce?{...e,sets:ns.length?ns:[{w:"",r:"",type:"normal",note:"",nt:"",drops:[]}],cs:Math.min(ex.cs,Math.max(0,ns.length-1))}:e)};})} style={{...B(false),color:C.rd,fontSize:12,padding:"4px 0",marginTop:8}}>Remove Set</button>}
</div>
<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:10}}>
<button onClick={()=>{if(ex.cs>0)sSS(s=>({...s,exs:s.exs.map((e,i)=>i===s.ce?{...e,cs:e.cs-1}:e)}));}} disabled={ex.cs===0} style={{...B(false),border:`1px solid ${C.bd}`,opacity:ex.cs===0?.4:1}}>Prev Set</button>
{isL?<button onClick={()=>sSS(s=>({...s,exs:s.exs.map((e,i)=>{if(i!==s.ce)return e;const l=e.sets[e.sets.length-1];return{...e,sets:[...e.sets,{w:l?l.w:"",r:l?l.r:"",type:"normal",note:"",nt:"",drops:[]}],cs:e.sets.length};})}))} style={{...B(true),background:C.or}}>+ Add Set</button>:<button onClick={()=>sSS(s=>({...s,exs:s.exs.map((e,i)=>i===s.ce?{...e,cs:e.cs+1}:e)}))} style={B(true)}>Next Set</button>}
<button onClick={()=>{if(sess.ce>0)sSS({...sess,ce:sess.ce-1});}} disabled={sess.ce===0} style={{...B(false),border:`1px solid ${C.bd}`,opacity:sess.ce===0?.4:1}}>Prev Exercise</button>
{sess.ce<tE-1?<button onClick={()=>sSS({...sess,ce:sess.ce+1})} style={{...B(true),background:C.gn}}>Next Exercise</button>:<button onClick={finS} style={{...B(true),background:C.gn}}>Finish</button>}
</div></div></div>;}
return <div style={{background:C.bg,minHeight:"100vh",color:C.tx,fontFamily:"system-ui"}}><div style={{padding:"20px 24px 0",maxWidth:800,margin:"0 auto"}}><div style={{display:"flex",alignItems:"center",justifyContent:"space-between",marginBottom:8,flexWrap:"wrap",gap:8}}><div><h1 style={{margin:0,fontSize:24,fontWeight:700}}>Watch Dashboard</h1><p style={{margin:"4px 0 0",color:C.dm,fontSize:13}}>Workout Tracker</p></div><div style={{display:"flex",alignItems:"center",gap:12}}>
  <span style={{color:C.dm,fontSize:13}}>{user.email}</span>
  <button onClick={handleSignOut} style={{padding:"8px 16px",borderRadius:8,border:"none",background:C.ac,color:"#fff",cursor:"pointer",fontSize:14,fontWeight:500}}>
    Sign Out
  </button>
</div></div>
<div style={{background:C.cd,borderRadius:10,padding:4,display:"flex",gap:4,border:`1px solid ${C.bd}`,flexWrap:"wrap",marginTop:16}}>{[["today","Today"],["split","Schedule"],["templates","Templates"],["overview","History"],["prs","PRs"]].map(([k,l])=><button key={k} style={B(view===k)} onClick={()=>sv(k)}>{l}</button>)}</div></div>
<div style={{padding:"16px 24px",maxWidth:800,margin:"0 auto"}}>
{view==="today"&&<><div style={{...CR,borderColor:C.ac,position:"relative",overflow:"hidden"}}><div style={{position:"absolute",top:0,left:0,right:0,height:3,background:C.ac}}/><div style={{marginBottom:12}}><label style={{fontSize:11,color:C.dm,display:"block",marginBottom:6}}>Workout Date</label><input type="date" style={{...IN,fontSize:14,width:"auto"}} value={workoutDate} onChange={e=>sWD(e.target.value)} max={td}/></div><div style={{display:"flex",justifyContent:"space-between",alignItems:"flex-start"}}><div><div style={{fontSize:13,color:C.dm,marginBottom:4}}>{workoutDate===td?tDay:new Date(workoutDate+"T12:00:00").toLocaleDateString("en-US",{weekday:"long"})}</div><DD open={tDd} onClose={()=>sTD(false)} trigger={<button onClick={()=>sTD(!tDd)} style={{background:"none",border:"none",color:C.tx,fontSize:22,fontWeight:700,cursor:"pointer",padding:0,display:"flex",alignItems:"center",gap:8}}>{tTmpl.name} &#9660;</button>}><div style={{padding:"4px 8px",fontSize:10,color:C.dm,fontWeight:700,textTransform:"uppercase"}}>Just for today</div>{tmpls.map(t=><DI key={t.id} active={tTid===t.id} onClick={()=>{sTO(t.id===sched[tDay]?null:t.id);sTD(false);}}>{t.name}</DI>)}{tOvr&&<><div style={{height:1,background:C.bd,margin:"4px 0"}}/><DI onClick={()=>{sTO(null);sTD(false);}} color={C.yl}>Reset</DI></>}</DD>{tOvr&&<div style={{fontSize:11,color:C.yl,marginTop:4}}>Today only</div>}</div>
{tTmpl.exercises.length>0&&(pausedSess?<button onClick={()=>{sSS(pausedSess);sPS(null);}} style={{...B(true),background:C.or,fontWeight:600}}>Continue Workout</button>:selDateW?<button onClick={()=>startS(null,selDateW,workoutDate)} style={{...B(true),background:C.ac,fontWeight:600}}>{selDateW.exercises.every(e=>e.sets.length>=1)?"Edit Completed":"Edit Workout"}</button>:<button onClick={()=>startS(tTmpl,null,workoutDate)} style={{...B(true),background:C.gn,fontWeight:600}}>Start Workout</button>)}</div>
{tTmpl.exercises.length>0?<div style={{marginTop:16}}>{tTmpl.exercises.map((e,i)=><div key={i} style={{padding:"10px 0",borderTop:i?`1px solid ${C.bd}`:"none",display:"flex",justifyContent:"space-between"}}><div style={{display:"flex",gap:10}}><span style={{color:C.dm,width:20}}>{i+1}</span><span>{e.name}</span></div><span style={{color:C.dm,fontSize:12}}>{e.sets} sets</span></div>)}</div>:<p style={{color:C.dm,marginTop:12}}>Rest day</p>}</div>
<div style={{...CR,display:"flex",alignItems:"center",gap:16,padding:16}}><div style={{fontSize:32,fontWeight:700,color:streak>0?C.gn:C.dm}}>🔥 {streak}</div><div><div style={{fontWeight:600}}>Day Streak</div><div style={{color:C.dm,fontSize:12}}>Consecutive workout days</div></div></div>
<h3 style={{fontSize:15,fontWeight:600,margin:"16px 0 12px"}}>This Week</h3>
<div style={{display:"grid",gridTemplateColumns:"repeat(7,1fr)",gap:8}}>{DAYS.map((day,i)=>{const t=gT(sched[day]),ws=wkSt[i];let bc=C.bd,bg=C.cd,dc=C.dm,lc=ws.isR?C.dm:C.tx;if(ws.isTd){bc=C.ac;bg=C.ac+"11";dc=C.ac;}if(ws.w){bc=C.gn;bg=C.gn+"11";lc=C.gn;}else if(ws.past&&!ws.isR){bc=C.rd;bg=C.rd+"08";lc=C.rd;}return <div key={day} style={{...CR,padding:12,textAlign:"center",marginBottom:0,borderColor:bc,background:bg}}><div style={{fontSize:11,color:dc,fontWeight:600,marginBottom:4}}>{day.slice(0,3)}</div><div style={{fontSize:12,color:lc}}>{t.name}</div>{ws.pr&&ws.w&&<div style={{marginTop:4}}>⭐<div style={{fontSize:9,color:C.gd,fontWeight:700}}>New PR</div></div>}</div>;})}</div></>}
{view==="split"&&<><h2 style={{margin:"0 0 16px",fontSize:20}}>Weekly Schedule</h2>{DAYS.map(day=>{const t=gT(sched[day]),isO=oDd===day;return <div key={day} style={{...CR,display:"flex",alignItems:"center",gap:16}}><span style={{color:C.dm,width:36}}>{day.slice(0,3)}</span><DD open={isO} onClose={()=>sOD(null)} trigger={<button onClick={()=>sOD(isO?null:day)} style={{background:C.inn,border:`1px solid ${isO?C.ac:C.bd}`,borderRadius:8,padding:"8px 14px",color:C.tx,cursor:"pointer",fontWeight:600,display:"flex",alignItems:"center",gap:8}}>{t.name} ▼</button>}>{tmpls.map(tm=><DI key={tm.id} active={sched[day]===tm.id} onClick={()=>{const newS={...sched,[day]:tm.id};sS(newS);saveSchedule(newS);sOD(null);}}>{tm.name}</DI>)}</DD></div>;})}</>}
{view==="templates"&&<><div style={{display:"flex",justifyContent:"space-between",marginBottom:16}}><h2 style={{margin:0,fontSize:20}}>Templates</h2>{!shNT&&<button onClick={()=>sSNT(true)} style={{...B(true),fontSize:13}}>+ New</button>}</div>
{shNT&&<div style={{...CR,borderColor:C.gn}}><div style={{display:"flex",gap:8}}><input style={IN} placeholder="Template name" value={nTN} onChange={e=>sNTN(e.target.value)} onKeyDown={e=>e.key==="Enter"&&cTmpl()}/><button onClick={cTmpl} style={{...B(true),background:C.gn}}>Create</button><button onClick={()=>{sSNT(false);sNTN("");}} style={{...B(false),color:C.dm}}>Cancel</button></div></div>}
{tmpls.filter(t=>t.name!=="Rest").map(t=>{const isE=eTmpl===t.id;return <div key={t.id} style={{...CR,borderColor:isE?C.ac:C.bd}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:isE?16:0}}><div style={{display:"flex",alignItems:"center",gap:12}}>{isE?<input style={{...IN,maxWidth:250,fontWeight:600}} value={t.name} onChange={e=>uTN(t.id,e.target.value)}/>:<span style={{fontWeight:600}}>{t.name}</span>}{!isE&&<span style={{fontSize:12,color:C.dm}}>{t.exercises.length} ex</span>}</div><div style={{display:"flex",gap:8}}>{!isE&&<button onClick={()=>startS(t)} style={{...B(false),color:C.gn,fontSize:12}}>▶</button>}<button onClick={()=>sET(isE?null:t.id)} style={{...B(false),color:isE?C.gn:C.ac,fontSize:13}}>{isE?"Done":"Edit"}</button>{isE&&<button onClick={()=>{if(confirm("Delete?"))dTmpl(t.id);}} style={{...B(false),color:C.rd,fontSize:12}}>Del</button>}</div></div>
{isE?<div>{t.exercises.map((ex,i)=><div key={i} style={{display:"flex",gap:8,alignItems:"center",marginBottom:8}}><span style={{color:C.dm,width:20}}>{i+1}</span><input style={{...IN,flex:1}} value={ex.name} onChange={e=>uTEx(t.id,i,"name",e.target.value)}/><input type="number" style={{...IN,width:50,textAlign:"center"}} value={ex.sets} onChange={e=>uTEx(t.id,i,"sets",Math.max(1,+e.target.value||1))}/><button onClick={()=>mTEx(t.id,i,-1)} style={{background:"none",border:"none",color:C.dm,opacity:i===0?.3:1}}>↑</button><button onClick={()=>mTEx(t.id,i,1)} style={{background:"none",border:"none",color:C.dm,opacity:i>=t.exercises.length-1?.3:1}}>↓</button><button onClick={()=>rTEx(t.id,i)} style={{background:"none",border:"none",color:C.rd}}>x</button></div>)}<button onClick={()=>aTEx(t.id)} style={{...B(false),color:C.gn,fontSize:12,marginLeft:28}}>+ Exercise</button></div>:t.exercises.length>0&&<div style={{marginTop:8,color:C.dm,fontSize:13}}>{t.exercises.map(e=>`${e.name}(${e.sets})`).join(" · ")}</div>}</div>;})}
<h3 style={{fontSize:17,fontWeight:600,margin:"28px 0 12px"}}>Exercise Library</h3>
<div style={{display:"flex",justifyContent:"space-between",marginBottom:12}}><span style={{color:C.dm,fontSize:13}}>By muscle group</span>{!newLibEx&&<button onClick={()=>sNLE({n:"",g:"Other"})} style={{...B(true),fontSize:13}}>+ New Exercise</button>}</div>
{newLibEx&&<div style={{...CR,borderColor:C.gn}}><div style={{display:"flex",gap:8}}><input style={IN} placeholder="Exercise name" value={newLibEx.n} onChange={e=>sNLE({...newLibEx,n:e.target.value})}/><select style={{...IN,width:120}} value={newLibEx.g} onChange={e=>sNLE({...newLibEx,g:e.target.value})}>{["Back","Biceps","Calves","Chest","Hamstrings","Quads","Shoulders","Triceps","Other"].map(g=><option key={g}>{g}</option>)}</select><button onClick={()=>{if(newLibEx.n.trim()){MG[newLibEx.n.trim()]=newLibEx.g;sT([...tmpls]);sNLE(null);}}} style={{...B(true),background:C.gn}}>Add</button><button onClick={()=>sNLE(null)} style={{...B(false),color:C.dm}}>X</button></div></div>}
{Object.entries(exByMG).sort().map(([g,xs])=><div key={g} style={{marginBottom:12}}><div style={{fontSize:12,color:C.ac,fontWeight:700,textTransform:"uppercase",marginBottom:6}}>{g}</div><div style={{display:"flex",flexWrap:"wrap",gap:6}}>{xs.map(n=><span key={n} style={{padding:"4px 12px",borderRadius:20,border:`1px solid ${C.bd}`,fontSize:13,background:C.inn}}>{n}</span>)}</div></div>)}</>}
{view==="overview"&&<><div style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12,marginBottom:20}}>{[["Workouts",hist.length,C.ac],["Exercises",allEx.length,C.gn],["Volume",(hist.reduce((t,w)=>t+w.exercises.reduce((t2,e)=>t2+vol(e),0),0)/1000).toFixed(0)+"k",C.rd],["Streak","🔥"+streak,C.or]].map(([l,v,c],i)=><div key={i} style={{...CR,textAlign:"center",padding:16}}><div style={{fontSize:22,fontWeight:700,color:c}}>{v}</div><div style={{fontSize:11,color:C.dm,marginTop:4}}>{l}</div></div>)}</div>
{perfData.length>1&&<PerfCharts perfData={perfData} prDates={prDates} latestPerf={latestPerf}/>}
<h3 style={{margin:"0 0 12px",fontSize:15,fontWeight:600}}>History</h3>
{[...hist].reverse().map(w=><div key={w.id} style={{...CR,cursor:"pointer"}} onClick={()=>{sSW(w);sv("detail");}} onMouseEnter={e=>e.currentTarget.style.borderColor=C.ac} onMouseLeave={e=>e.currentTarget.style.borderColor=C.bd}><div style={{display:"flex",justifyContent:"space-between"}}><div><div style={{fontWeight:600}}>{w.name}</div><div style={{color:C.dm,fontSize:13}}>{fd(w.date)}</div></div><div style={{textAlign:"right"}}><div style={{fontSize:13,color:C.gn}}>{w.exercises.length} ex</div><div style={{fontSize:12,color:C.dm}}>{w.exercises.reduce((t,e)=>t+vol(e),0).toLocaleString()} lbs</div></div></div></div>)}</>}
{view==="detail"&&selW&&<><button onClick={()=>sv("overview")} style={{...B(false),color:C.ac,padding:"4px 0",marginBottom:12}}>← Back</button><h2 style={{margin:0}}>{selW.name}</h2><p style={{color:C.dm,fontSize:13,marginBottom:16}}>{fd(selW.date)}</p>
{selW.exercises.map((ex,i)=><div key={i} style={CR}><h4 style={{margin:"0 0 12px",color:C.gn}}>{ex.name}</h4><div style={{display:"grid",gridTemplateColumns:"40px 1fr 1fr 1fr",gap:8,fontSize:12}}><div style={{color:C.dm,fontWeight:600}}>Set</div><div style={{color:C.dm,fontWeight:600}}>Wt</div><div style={{color:C.dm,fontWeight:600}}>Reps</div><div style={{color:C.dm,fontWeight:600}}>Vol</div>{ex.sets.map((s,j)=><React.Fragment key={j}><div style={{color:C.dm}}>{j+1}</div><div>{s.w}lbs</div><div>{s.r}</div><div style={{color:C.ac}}>{(s.r*s.w).toLocaleString()}</div>{s.drops&&s.drops.map((d,di)=><React.Fragment key={di}><div style={{color:C.or}}>↓</div><div style={{color:C.or}}>{d.w}</div><div style={{color:C.or}}>{d.r}</div><div style={{color:C.or}}>{d.w*d.r}</div></React.Fragment>)}</React.Fragment>)}</div><div style={{marginTop:12,paddingTop:12,borderTop:`1px solid ${C.bd}`,display:"flex",justifyContent:"space-between",fontSize:13}}><span style={{color:C.dm}}>Volume</span><span style={{fontWeight:600}}>{vol(ex).toLocaleString()} lbs</span></div></div>)}</>}
{view==="prs"&&<><h2 style={{margin:"0 0 16px"}}>Personal Records</h2><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}>{Object.entries(prs).sort(([a],[b])=>(favs[b]?1:0)-(favs[a]?1:0)||a.localeCompare(b)).map(([name,d])=>{const iF=favs[name],imp=d.prev>0?d.best-d.prev:0,pct=d.prev>0?((imp/d.prev)*100).toFixed(1):0,isX=expPR===name;
return <div key={name} style={{...CR,borderColor:iF?C.gd:C.bd,marginBottom:0,gridColumn:isX?"1/-1":"auto"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:8}}><button onClick={()=>sEP(isX?null:name)} style={{background:"none",border:"none",color:C.tx,cursor:"pointer",padding:0,fontWeight:600,fontSize:15}}>{name}</button><button onClick={()=>sF({...favs,[name]:!iF})} style={{background:"none",border:"none",cursor:"pointer",fontSize:18}}>{ iF?"⭐":"☆"}</button></div>
<div style={{display:"flex",gap:12,flexWrap:"wrap",marginBottom:8}}><div><div style={{fontSize:10,color:C.dm,textTransform:"uppercase"}}>1RM</div><div style={{fontSize:24,fontWeight:700,color:C.gn}}>{d.best}<span style={{fontSize:12,fontWeight:400}}>lbs</span></div></div>{imp>0&&<div><div style={{fontSize:10,color:C.dm,textTransform:"uppercase"}}>Gain</div><div style={{fontSize:16,fontWeight:700,color:C.ac}}>+{imp}<span style={{fontSize:11}}>lbs</span></div><div style={{fontSize:11,color:C.gn}}>↑{pct}%</div></div>}<div><div style={{fontSize:10,color:C.dm,textTransform:"uppercase"}}>Date</div><div style={{fontSize:13,marginTop:4}}>{fd(d.bDate)}</div></div></div>
{isX?<div style={{marginTop:8}}><ResponsiveContainer width="100%" height={140}><LineChart data={d.hist}><CartesianGrid strokeDasharray="3 3" stroke={C.bd}/><XAxis dataKey="fd" tick={{fill:C.dm,fontSize:10}}/><YAxis tick={{fill:C.dm,fontSize:10}}/><Tooltip contentStyle={{background:C.cd,border:`1px solid ${C.bd}`,borderRadius:8,color:C.tx,fontSize:12}} formatter={v=>[v+" lbs","1RM"]}/><Line type="monotone" dataKey="e1rm" stroke={C.gn} strokeWidth={2} dot={p=>{const isPR=p.payload.e1rm===d.best;return <circle cx={p.cx} cy={p.cy} r={isPR?5:2} fill={isPR?C.gd:C.gn} stroke={isPR?"#fff":"none"} strokeWidth={isPR?2:0}/>;}} /></LineChart></ResponsiveContainer></div>:d.hist.length>1&&<ResponsiveContainer width="100%" height={60}><LineChart data={d.hist}><XAxis hide/><YAxis hide domain={["dataMin-10","dataMax+10"]}/><Line type="monotone" dataKey="e1rm" stroke={C.ac} strokeWidth={2} dot={{fill:C.ac,r:2}}/></LineChart></ResponsiveContainer>}
</div>;})}</div>{!Object.keys(prs).length&&<div style={{...CR,textAlign:"center",color:C.dm,padding:40}}>Complete workouts to see PRs</div>}</>}
</div></div>;}
export default function App() {
  return (
    <AuthWrapper>
      {(user, handleSignOut) => <Dashboard user={user} handleSignOut={handleSignOut} />}
    </AuthWrapper>
  );
}